//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.13 at 12:38:16 AM IST 
//


package com.sample.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sample.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 construct new instances of the Java representation 
 for XML content. The Java representation of XML 
 content can consist of schema derived interfaces 
 and classes representing the binding of schema 
 type definitions, element declarations and model 
 groups.  Factory methods for each of these are 
 provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Company_QNAME = new QName("http://morning.com/", "company");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sample.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link Staff }
     * 
     */
    public Staff createStaff() {
        return new Staff();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Company }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://morning.com/", name = "company")
    public JAXBElement<Company> createCompany(Company value) {
        return new JAXBElement<Company>(_Company_QNAME, Company.class, null, value);
    }

}
