//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 11:50:19 PM IST 
//


package choice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}homeAdress"/>
 *         &lt;element ref="{}officeAddress"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customer", propOrder = {
    "homeAdress",
    "officeAddress"
})
@XmlRootElement
public class Customer {

    protected HomeAdress homeAdress;
    protected OfficeAddress officeAddress;

    /**
     * Gets the value of the homeAdress property.
     * 
     * @return
     *     possible object is
     *     {@link HomeAdress }
     *     
     */
    public HomeAdress getHomeAdress() {
        return homeAdress;
    }

    /**
     * Sets the value of the homeAdress property.
     * 
     * @param value
     *     allowed object is
     *     {@link HomeAdress }
     *     
     */
    public void setHomeAdress(HomeAdress value) {
        this.homeAdress = value;
    }

    /**
     * Gets the value of the officeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link OfficeAddress }
     *     
     */
    public OfficeAddress getOfficeAddress() {
        return officeAddress;
    }

    /**
     * Sets the value of the officeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfficeAddress }
     *     
     */
    public void setOfficeAddress(OfficeAddress value) {
        this.officeAddress = value;
    }

}
